// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Pritesh-StocksDeveloper
  
//@version=5
strategy("Supertrend EMA Crossover", overlay=true, calc_on_every_tick = false)
  
//IP CONTROLS
EMA_LS = input.int(title="EMALS", defval=13, minval=1, maxval=200, step=1)
EMA_LL = input.int(title="EMALL", defval=34, minval=1, maxval=200, step=1)

ATR_L = input.int(title="ATRL", defval=10, minval=1, maxval=100, step=1)
MULTI = input.int(title="MULTI", defval=3, minval=1, maxval=100, step=1)

// INDICATORS
[supertrend, direction] = ta.supertrend(MULTI, ATR_L)

EMA1 = ta.ema(close, EMA_LS)
EMA2 = ta.ema(close, EMA_LL)

// Plot
plot(EMA1, color=color.blue)
plot(EMA2, color=color.green)
plot(supertrend, color=color.red)

// Buy conditions
buy = ta.crossover(close, supertrend) and EMA1 > EMA2
if(buy)
    strategy.entry("Long", strategy.long, 1, stop=strategy.position_avg_price-strategy.position_avg_price*0.05)

// Sell Condition
sell = ta.crossunder(close, supertrend) and EMA1 < EMA2
if(sell)
    strategy.exit("Long", profit=strategy.position_avg_price+strategy.position_avg_price*0.5, loss=strategy.position_avg_price-strategy.position_avg_price*0.2)